### ISSUE TITLE
Not Able to retrive while running in browser (tonicdev.com

### ISSUE THREAD

**Issue by pabitra25** [facundoolano/google-play-scraper#109]
Hi 

I am not be able to download the reviews retrieved by the scraper . I am using in browser pull in www.tonicdev.com. (Screen Shot attached)

Also how can i download it in csv format .   

Second issue is that its only retrieving 40 reviews whereas in the App there are more than 1000 reviews , how can i pull all of them 

Please help 
![screen shot 2016-08-21 at 12 09 55 pm](https://cloud.githubusercontent.com/assets/9796078/17835766/c77941ea-6798-11e6-9ea0-8046296aef85.png)

**Comment by facundoolano** [comment]
I'm not familiar with that tonic thing, so I can't help much there. But it looks as it's working since it's printing "Retrieved 40 reviews". If you want to see the text print that instead of the result length. It looks like you need to get more familiar with

**Comment by tolmasky** [comment]
Hi @pabitra25, the problem is that gplay.reviews returns a promise (which is why you see the result as a "Promise {}", and then in the then clause it seems to work correctly). If you *await* the promise you will see your reviews, as I've shown here: https://tonicdev.com/tolmasky/57bb9a1ed322921400194dfa

**Comment by tolmasky** [comment]
Not sure if you tried that link before @pabitra25, but it was broken and now works. Apologies. https://tonicdev.com/tolmasky/57bb9a1ed322921400194dfa
