### ISSUE TITLE
Developer parsing is broken

### ISSUE THREAD

**Issue by yura415** [facundoolano/google-play-scraper#112]

**Comment by facundoolano** [comment]
Can you elaborate?

**Comment by yura415** [comment]
Sry.. Google apeear to have recently change their developer page url to https://play.google.com/store/apps/dev?id= instead of https://play.google.com/store/apps/developer?id=.
As you can see here https://github.com/facundoolano/google-play-scraper/blob/dev/lib/developer.js#L15 url is still in old format so none of the requests come with status 200.

If you'd open https://play.google.com/store/apps/developer?id=6695914693084197974 and https://play.google.com/store/apps/dev?id=6695914693084197974 you can see the difference.

**Comment by facundoolano** [comment]
Thanks, I'll try to fix it today.

**Comment by facundoolano** [comment]
@yura415 I'm checking this now and it looks like the `/developer` page is still working. The thing is that endpoint works with the developer name as the id (rather than a number like the `/dev` page). Using your example:

https://play.google.com/store/apps/developer?id=Intellijoy%20Educational%20Games%20for%20Kids

Using the module:

```js
> gplay.developer({devId: 'Intellijoy Educational Games for Kids'}).then(console.log)
Promise { <pending> }
> [ { url: 'https://play.google.com/store/apps/details?id=com.intellijoy.android.reading.free',
    appId: 'com.intellijoy.android.reading.free',
    title: 'Kids Learn to Read (Lite)',
    summary: 'A must-have sequel to our best-selling Kids ABC Phonics',
    developer: 'Intellijoy Educational Games for Kids',
    icon: '//lh3.googleusercontent.com/p19nyn88_sJrHuPCnAltYEn1EXUoko7YKOM97i0I6bLz8F6zK-C9FC3H6Pmwf3ESy_A=w340',
    score: 4,
    price: '0',
    free: true },
    ...
]
```

I'm closing this and opening a different issue so we start supporting both types of ids.
