### ISSUE TITLE
Ignore Emojis in Reviews?

### ISSUE THREAD

**Issue by gujukrish** [facundoolano/google-play-scraper#134]
Is there a way to ignore emojis within reviews?
The emoticons are messing up my raw data output, they seem to be acting as "delimiters."

**Comment by facundoolano** [comment]
Can you show me an example result of the review method including emojis? Also, can you clarify how does it break (is this module that breaks or your code and how).

**Comment by gujukrish** [comment]
**Here is my code:**
var bArray = ["_insert app domains here_"];
var bArrayLength = bArray.length;

for(var b = 0; b < bArrayLength; b++) {

for(var i=0; i<1; i++){
var gplay = require('google-play-scraper');

gplay.reviews({
appId: bArray[b],
page: i,
sort: gplay.sort.NEWEST,
throttle: 10
})
.then(console.log)
.catch(console.log);
}
}

**Console output is then copy pasted into a .txt file**
[Console output.txt](https://github.com/facundoolano/google-play-scraper/files/679690/Console.output.txt)

**That text file is then imported to excel with "|" as a delimiter**
[Reviews.xlsx](https://github.com/facundoolano/google-play-scraper/files/679689/Reviews.xlsx)

Please see cell A109 where the first error occurs... the correlating review is shown in the screenshot below from the .txt file.
![screen shot 2016-12-31 at 10 07 10 am](https://cloud.githubusercontent.com/assets/24703455/21578094/8031f2f8-cf41-11e6-92ac-8ffad4fa4e7c.png)

It may not be an emoticon issue at all, but thats the only issue I can think of.
Thanks for your help.

**Comment by facundoolano** [comment]
The text with the emojis seems to be properly generated, I can't tell about what excel does with that. I'd suggest you try to manually remove the emojis from the text (maybe taking a shorter amount of results) to make sure that's the issue.

If it really is the emojis that are causing your issue, you may want to google around how to remove it from the js strings after getting the reviews and before exporting to excel.

I'm closing this since it doesn't look like an issue with the module, but feel free to add more information or questions if you find out something else.
