### ISSUE TITLE
feature: add an option to the search/list functions to include app permissions of each result

### ISSUE THREAD

**Issue by AdamSlack** [facundoolano/google-play-scraper#160]
When setting ```fullDetail: true``` should the app's permissions not be included?

Example usage:
```
gplay.search({
        term: search_term,
        num: number_of_apps,
        throttle: per_second,
        fullDetail: true
    });
```

**Comment by facundoolano** [comment]
Permissions are taken via a separate request than the application details, so including them would mean an extra request per app. I imagine duplicating the cost of the current `fullDetail` operations wouldn't be desirable in most cases, so to include permissions I'd rather add a separate option like `withPermissions` or something like that.

**Comment by facundoolano** [comment]
I'll change the issue title to reflect that.

**Comment by ormeno** [comment]
Hello , thanks for your code, it's great.

I write because the modification does not work me to get "list" with "permissions", I get the following error

_"   _throw new Error ('First argument to _arity must be a non-negative integer no greater than ten ');

_Error: First argument to _arity must be to non-negative integer no greater than tin
    at _arity (D: \ several \ Uni \ project \ node_modules \ google-play-scraper \ node_modu
les \ ramda \ dist \ ramda.js: 87: 19)
    at D: \ several \ Uni \ project \ node_modules \ google-play-scraper \ node_modules \ ramd
a \ dist \ ramda.js: 5003: 20
    at Object.f2 [as partial] (D: \ several \ Uni \ project \ node_modules \ google-play-s
craper \ node_modules \ ramda \ dist \ ramda.js: 473: 22)
    at Object. <anonymous> (D: \ several \ Uni \ project \ node_modules \ google-play-scrap
er \ index.js: 9: 21)
    at Module._compile (module.js: 413: 34)
    at Object.Module._extensions..js (module.js: 422: 10)
    at Module.load (module.js: 357: 32)
    at Function.Module._load (module.js: 314: 12)
    at Module.require (module.js: 367: 17)
    at require (internal / module.js: 16: 19)_"__

It's my first time with node js and I do not know how to solve it,  Can to be the changes start from a different version of the development?

Thanks so much

Rodrigo

**Comment by facundoolano** [comment]
@ormeno please create a separate issue for this, and include all the required information.

**Comment by ormeno** [comment]
Don`t worry, i've solved it. I had a problem of versions, i updated nodejs to 8.11.2 and version google-play-scraper to 3.1.1 and then it  works.
