### ISSUE TITLE
gplay.category.APP_WIDGETS no longer working

### ISSUE THREAD

**Issue by alexiskattan** [facundoolano/google-play-scraper#176]
All the others work really well but `gplay.category.APP_WIDGETS` returns 

> { Error: App not found (404)
>     at C:\me\node_modules\google-play-scraper\lib\utils\request.js:39:21
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) is404: true }

**Comment by facundoolano** [comment]
It looks like that category has been removed:

works: https://play.google.com/store/apps/category/GAME_ROLE_PLAYING 
doesn't work: https://play.google.com/store/apps/category/APP_WIDGETS

Can you send a PR removing it? Also if you have the time can you review the list of categories in https://play.google.com/store/apps to see if the code is up to date with it?

**Comment by icaroponce** [comment]
Have you guys considered a method to scrape the current categories on Gplay Store? We could then remove them as constants, or even let them there (since they don't depend on each other), but offering a possibility to get the current categories (which would demand one more request). I ask because the Google really update the categories, removing or adding new ones, not too often I know, but that happens.

**Comment by facundoolano** [comment]
That could make sense (assuming you only run it once and keep the results for a while). I'd be interested in knowing how categories are frequently used, I always thought about those constants as something you'd use statically in your code.

**Comment by elitebrain** [comment]
how can I get description include linebreak (e.g \n or <br>)

**Comment by facundoolano** [comment]
I've removed the APP_WIDGETS category and created #178 so it's easier to spot outdated categories. I think that's good enough solution.
