### ISSUE TITLE
Reviews aren't cleaning "full review" text for another languages.

### ISSUE THREAD

**Issue by evertonoliveira1** [facundoolano/google-play-scraper#185]
When I request the route **'reviews/:appId'**, using parameters **hl="pt-BR"**, the response has "resenha completa" (it means full review in portuguese) into the text, I saw you're removing 'full review' by regex, but if the reviews are in another language, it doesn't clean the text into the class **<a class="id-no-nav play-button tiny" href="#" target="_blank">**. I've implemented a possible solution. Soon I'll create a PR for this.

**Comment by facundoolano** [comment]
Sure, a PR is welcome!

**Comment by facundoolano** [comment]
On further review, I noticed this was already fixed [here](https://github.com/facundoolano/google-play-scraper/commit/0fcc28e3c85dd6029fc27dc074c214db1ad25ef9), so you must be using an old version of this library. If your issue is related to google-play-api please open an issue there (or send a PR to update to the newest version).
