### ISSUE TITLE
Request for an app review after certain pages is not working!

### ISSUE THREAD

**Issue by Laksh47** [facundoolano/google-play-scraper#248]
* Operating System: Ubuntu 16.04
* Node version: 8.11.2
* google-play-scraper version: 4.0.0

### Description: 
After some pages of crawling, any request we make fails
I have given an example here for google maps(works until the page is 111). Fails afterwards!!

### Example code:
```js
gplay.reviews({
        appId: "com.google.android.apps.maps",
        page: 200,
        sort: gplay.sort.NEWEST
      }).then((data) => {
          console.log(data.length);

          if (data.length > 0) {
            // do something
          }
        }).catch((err) => {
          console.log(err);
          console.log("failed" );
        });
```

### Error message:

```
Error: Error requesting Google Play:undefined
    at node_modules/google-play-scraper/lib/utils/request.js:43:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by facundoolano** [comment]
Please upgrade to the latest google play scraper version.

**Comment by tarunima** [comment]
Hi,
Using google-play-scraper version 6.2.3 but still unable to read reviews beyond page 111. No error. Just a blank object.
I can however visually scroll down on the app page on play store to see comments older than those on page 111.

This doesn't seem to be a throttling issue since even if I pass only one page as argument, if page > 111, no object is returned by the API. Any fix for this?
