### ISSUE TITLE
Problem with countries in search

### ISSUE THREAD

**Issue by ChayaGel** [facundoolano/google-play-scraper#551]
after all fixes in mapping from the "pull requests",
my search back to work.

but there are some strange problems:
search with country "be" (belgium) returns empty array- [], (maybe another countries)

**Comment by knirpsfass** [comment]
I've debugged it a little bit. Seems like european? countries do have an additional
"About the result" information which shifts the index of the apps array by 1.
<img width="2212" alt="Screenshot 2022-05-31 at 13 56 16" src="https://user-images.githubusercontent.com/42298776/171167531-cf981ac4-17e3-4a97-992d-82b3443198a4.png">
 So the mapping for the apps would be 
```apps: ['ds:4', 0, 1, 1, 22, 0]```
instead of
```apps: ['ds:4', 0, 1, 0, 22, 0]```

example request for still working request: 
https://play.google.com/store/search?q=test&c=apps&hl=en&gl=US

example request for not working request:
https://play.google.com/store/search?q=test&c=apps&hl=en&gl=DE

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by knirpsfass** [comment]
works with 9.0.0

**Comment by knirpsfass** [comment]
I fucked up really hard on the test. Really sorry for that. Issue is still present but now 
` "message": "Cannot read properties of undefined (reading 'map')"` is returned
