### ISSUE TITLE
I've noticed the icon and screenshot URLs have the http: cut off from them.

### ISSUE THREAD

**Issue by EasyGitHub99** [facundoolano/google-play-scraper#58]
I've noticed the icon and screenshot URLs have the http: cut off from them.

The URL for snapchat icon for example is this:
"//lh4.ggpht.com/vdK_CsMSsJoYvJpYgaj91fiJ1T8rnSHHbXL0Em378kQaaf_BGyvUek2aU9z2qbxJCAFV=w300"

Just thought I'd let you know in case you didn't want that.

**Comment by karvounis** [comment]
Oh that is true. Thank you for pointing it out. @facundoolano do you know what causes it and how can be fixed?

**Comment by EasyGitHub99** [comment]
I can try to use some javascript to simply add http: to the start of the urls. I'll try to make a commit today

**Comment by karvounis** [comment]
@EasyGitHub99 What if the url has https instead of http? I think we should think of a better solution before actually proceed with your suggestion.

**Comment by facundoolano** [comment]
Have you checked the source of the Google play page? If they don't use http/https then we shouldn't either

**Comment by karvounis** [comment]
<div class="cover-container"> <img class="cover-image" src="//lh3.googleusercontent.com/iJUn7YncJwy2BMKvTp5d9OFZCHkVKN2GemxR-rp3jggPcGE2xEvS26CUAbUrFmfV1rA9=w300-rw" alt="Cover art" aria-hidden="true" itemprop="image"> </div>

Source code has no http/https. If I remember correctly, a few weeks back the screenshots and icon urls started with http/https so my guess is that they recently changed the format. So, should we leave the code as it is?

**Comment by facundoolano** [comment]
AFAIK it's still a valid URL, I don't see the point of forcing a protocol if Google doesn't.

**Comment by cscatolini** [comment]
There is no protocol in the images url so the page will use the correct protocol depending o how you access it. For example, if you access https://play.google.com/... it will use https to fetch the images. This way you avoid errors such as "The page at 'https://play.google.com/...' was loaded over HTTPS, but requested an insecure image". The same reasoning goes for the http protocol. 
@facundoolano I suggest you close this issue since it is not really an issue :)
