### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#631]
In case someone has the time (I don't), it would be very helpful to get the unit tests back passing. This would simplify the PR review and merge process since it would make it obvious when code changes break things.

**Comment by tpwatson** [comment]
I'm working on this, but the comments are failing. I don't know if comments are even available anymore, I don't remember where they are, or what they are comments for/about. I'm not sure if we can still even get comments.

**Comment by facundoolano** [comment]
Hey @tpwatson I'm not positive but I think the comments field used to include the inline review texts that were loaded on the main app page (as opposed to the full review list exposed by the `reviews` method that comes from a separate google play endpoint).

So as an example, for [this app](https://play.google.com/store/apps/details?id=com.rvappstudios.math.kids.counting) it would be these reviews at the bottom:

![image](https://github.com/facundoolano/google-play-scraper/assets/1040941/ddf13d5a-da7c-43ef-b090-6c9b42ca3ddc)

**Comment by facundoolano** [comment]
Example from an earlier version of the README:

https://github.com/facundoolano/google-play-scraper/blob/84f5e933ff4b7199a0ccc079a81a522bf4580aa3/README.md?plain=1#L75

**Comment by tpwatson** [comment]
Thanks for the clarification. I have all tests passing, all though randomly the throttle test fails due to a timeout error. I'm not sure if it's because we still need to get got updated. But the requests probably are not returning fast enough sometimes.

**Comment by facundoolano** [comment]
are you already overriding the timeout threshold (as done [here](https://github.com/facundoolano/google-play-scraper/blob/main/package.json#LL7C20-L7C34))?

**Comment by tpwatson** [comment]
No I just left it as is.

I thought I had them all passing but running into trouble with suggested search tests failing. Trying to figure out how to get the mappings working.

**Comment by tpwatson** [comment]
So I've figured out how to count the mappings in an easier way, if I can actually fix the mapping issue I'll document it in the code for future use. But here is work with mappings and count them:

Get a full copy of the AF_initDataCallback object, its not JSON but you can use a Javascript object to JSON converter:

https://www.convertsimple.com/convert-javascript-to-json/
Paste the JS object in that site and you'll get the JSON version.

Then copy the JSON version and take it to:
https://jsonpathfinder.com/
![Untitled](https://github.com/facundoolano/google-play-scraper/assets/8966870/5fc6da45-1d88-4a02-b716-fd1ad40ab904)

Then you can find out the position of each piece of data much easier.

But what I've gotten stumped on now, is that when you misspell a search term, like 'runing app' instead of 'running app' the mappings will be different from the correctly spelled results.

So I have the mappings to correctly get the data for suggested search, but I'm trying to figure out how to put that into the search.js file so that when the results page has "Searching instead for [correct spelling search term]" it will use the other set of mappings.

It's a lot to digest how the current codebase works, I'm struggling to figure it out 100%, especially because ramda is essentially a blackbox for me, but I'm trying.

**Comment by tpwatson** [comment]
Just got all 77 tests passing! 🎉
![Untitled](https://github.com/facundoolano/google-play-scraper/assets/8966870/558efe87-38a5-4004-ac5c-fe2f16488b10)

Going to try my best to refactor the code and submit the PR asap!

Hopefully its acceptable!

**Comment by facundoolano** [comment]
Closed by #649
