### ISSUE TITLE
Error while looping through the pages

### ISSUE THREAD

**Issue by suku-h** [facundoolano/google-play-scraper#81]
First of all. This is fantastic stuff. Thanks a lot.
I added a loop to the pages section to get all the reviews. For some reason, the code skips through few pages

for(var i=0; i<12; i++){ 
	gplay.reviews({
	    appId: 'shree.hindi.gymguide',
	    page: i,
	    sort: gplay.sort.NEWEST
	}).then(function(apps){
	    console.log(apps);
	}).catch(function(e){
	    console.log('There was an error fetching the reviews!');
	});
}

For this example the total number of reviews is 465 and the reviews that I get back are 165. Around 300 reviews go missing.

This is how the results start:
[]
[]
[]
[]
[]
[]
[ { userId: '117452886884331198702',
    userName: 'milind jiwane',
    date: 'November 13, 2015',
    score: 5,
    title: 'Very good',
    text: 'Nice...' },

The total number of empty json is 7 (6 in the beginning and 1 somewhere in the middle). Can you advise what can be done to rectify this?

**Comment by facundoolano** [comment]
About the 465/165: the 465 displayed in the app page are the *ratings*, that is the amount of people that gave 1, 2, 3, 4 or 5 star ratings. Reviews are only those who entered a review message apart from the star rating, that's why you see a difference there.

Let me check about the empty results you see at the beginning.

**Comment by facundoolano** [comment]
Checked. The other thing you need to take into account is that you are requesting reviews in a specific language at a time (english by default). So when you ask for 12 pages, you just don't have that many reviews in english and that's why you get a bunch of empty responses. Try with a big app like facebook and you'll see results for a lot of pages.

**Comment by suku-h** [comment]
Thanks for the prompt reply and clarification.
